/***********************************************************************************************************************
 * This file was generated by the MCUXpresso Config Tools. Any manual edits made to this file
 * will be overwritten if the respective MCUXpresso Config Tools is used to update this file.
 **********************************************************************************************************************/

/* clang-format off */
/*
 * TEXT BELOW IS USED AS SETTING FOR TOOLS *************************************
!!GlobalInfo
product: Pins v10.0
processor: MKE06Z128xxx4
package_id: MKE06Z128VLK4
mcu_data: ksdk2_0
processor_version: 10.0.0
pin_labels:
- {pin_num: '25', pin_signal: PTC2/KBI0_P18/FTM2_CH2/ADC0_SE10, label: X_INT_RESET, identifier: X_INT_RESET}
- {pin_num: '27', pin_signal: PTD6/KBI0_P30/UART2_RX, label: X_INT_HOLD, identifier: X_INT_HOLD}
- {pin_num: '47', pin_signal: PTE4/KBI1_P4, label: DAC_LOAD, identifier: DAC_LOAD}
- {pin_num: '20', pin_signal: PTE6/KBI1_P6, label: DAC_SD_X_COEFF, identifier: DAC_SD_X_COEFF}
- {pin_num: '21', pin_signal: PTE5/KBI1_P5, label: DAC_CLOCK, identifier: DAC_CLOCK}
- {pin_num: '32', pin_signal: PTC0/KBI0_P16/FTM2_CH0/ADC0_SE8, label: TRIGGER, identifier: TRIGGER}
- {pin_num: '4', pin_signal: PTH6/KBI1_P30, label: DAC_SD_Y_COEFF, identifier: DAC_SD_Y_COEFF}
- {pin_num: '24', pin_signal: PTC3/KBI0_P19/FTM2_CH3/ADC0_SE11, label: Y_INT_RESET, identifier: Y_INT_RESET}
- {pin_num: '26', pin_signal: PTD7/KBI0_P31/UART2_TX, label: Y_INT_HOLD, identifier: Y_INT_HOLD}
 * BE CAREFUL MODIFYING THIS COMMENT - IT IS YAML SETTINGS FOR TOOLS ***********
 */
/* clang-format on */

#include "fsl_common.h"
#include "fsl_port.h"
#include "fsl_gpio.h"
#include "pin_mux.h"

/* FUNCTION ************************************************************************************************************
 *
 * Function Name : BOARD_InitBootPins
 * Description   : Calls initialization functions.
 *
 * END ****************************************************************************************************************/
void BOARD_InitBootPins(void)
{
    BOARD_InitPins();
}

/* clang-format off */
/*
 * TEXT BELOW IS USED AS SETTING FOR TOOLS *************************************
BOARD_InitPins:
- options: {callFromInitBoot: 'true', coreID: core0, enableClock: 'true'}
- pin_list:
  - {pin_num: '64', peripheral: UART1, signal: RX, pin_signal: PTC6/KBI0_P22/UART1_RX/CAN0_RX}
  - {pin_num: '63', peripheral: UART1, signal: TX, pin_signal: PTC7/KBI0_P23/UART1_TX/CAN0_TX}
  - {pin_num: '25', peripheral: GPIOA, signal: 'GPIO, 18', pin_signal: PTC2/KBI0_P18/FTM2_CH2/ADC0_SE10, direction: OUTPUT}
  - {pin_num: '27', peripheral: GPIOA, signal: 'GPIO, 30', pin_signal: PTD6/KBI0_P30/UART2_RX, direction: OUTPUT}
  - {pin_num: '47', peripheral: GPIOB, signal: 'GPIO, 4', pin_signal: PTE4/KBI1_P4, direction: OUTPUT}
  - {pin_num: '20', peripheral: GPIOB, signal: 'GPIO, 6', pin_signal: PTE6/KBI1_P6, direction: OUTPUT}
  - {pin_num: '21', peripheral: GPIOB, signal: 'GPIO, 5', pin_signal: PTE5/KBI1_P5, direction: OUTPUT}
  - {pin_num: '32', peripheral: GPIOA, signal: 'GPIO, 16', pin_signal: PTC0/KBI0_P16/FTM2_CH0/ADC0_SE8, direction: OUTPUT}
  - {pin_num: '4', peripheral: GPIOB, signal: 'GPIO, 30', pin_signal: PTH6/KBI1_P30, direction: OUTPUT}
  - {pin_num: '24', peripheral: GPIOA, signal: 'GPIO, 19', pin_signal: PTC3/KBI0_P19/FTM2_CH3/ADC0_SE11, direction: OUTPUT}
  - {pin_num: '26', peripheral: GPIOA, signal: 'GPIO, 31', pin_signal: PTD7/KBI0_P31/UART2_TX, direction: OUTPUT}
 * BE CAREFUL MODIFYING THIS COMMENT - IT IS YAML SETTINGS FOR TOOLS ***********
 */
/* clang-format on */

/* FUNCTION ************************************************************************************************************
 *
 * Function Name : BOARD_InitPins
 * Description   : Configures pin routing and optionally pin electrical features.
 *
 * END ****************************************************************************************************************/
void BOARD_InitPins(void)
{

    gpio_pin_config_t TRIGGER_config = {
        .pinDirection = kGPIO_DigitalOutput,
        .outputLogic = 0U
    };
    /* Initialize GPIO functionality on pin PTA16 (pin 32) */
    GPIO_PinInit(BOARD_INITPINS_TRIGGER_GPIO_PORT, BOARD_INITPINS_TRIGGER_PIN, &TRIGGER_config);

    gpio_pin_config_t X_INT_RESET_config = {
        .pinDirection = kGPIO_DigitalOutput,
        .outputLogic = 0U
    };
    /* Initialize GPIO functionality on pin PTA18 (pin 25) */
    GPIO_PinInit(BOARD_INITPINS_X_INT_RESET_GPIO_PORT, BOARD_INITPINS_X_INT_RESET_PIN, &X_INT_RESET_config);

    gpio_pin_config_t Y_INT_RESET_config = {
        .pinDirection = kGPIO_DigitalOutput,
        .outputLogic = 0U
    };
    /* Initialize GPIO functionality on pin PTA19 (pin 24) */
    GPIO_PinInit(BOARD_INITPINS_Y_INT_RESET_GPIO_PORT, BOARD_INITPINS_Y_INT_RESET_PIN, &Y_INT_RESET_config);

    gpio_pin_config_t X_INT_HOLD_config = {
        .pinDirection = kGPIO_DigitalOutput,
        .outputLogic = 0U
    };
    /* Initialize GPIO functionality on pin PTA30 (pin 27) */
    GPIO_PinInit(BOARD_INITPINS_X_INT_HOLD_GPIO_PORT, BOARD_INITPINS_X_INT_HOLD_PIN, &X_INT_HOLD_config);

    gpio_pin_config_t Y_INT_HOLD_config = {
        .pinDirection = kGPIO_DigitalOutput,
        .outputLogic = 0U
    };
    /* Initialize GPIO functionality on pin PTA31 (pin 26) */
    GPIO_PinInit(BOARD_INITPINS_Y_INT_HOLD_GPIO_PORT, BOARD_INITPINS_Y_INT_HOLD_PIN, &Y_INT_HOLD_config);

    gpio_pin_config_t DAC_LOAD_config = {
        .pinDirection = kGPIO_DigitalOutput,
        .outputLogic = 0U
    };
    /* Initialize GPIO functionality on pin PTB4 (pin 47) */
    GPIO_PinInit(BOARD_INITPINS_DAC_LOAD_GPIO_PORT, BOARD_INITPINS_DAC_LOAD_PIN, &DAC_LOAD_config);

    gpio_pin_config_t DAC_CLOCK_config = {
        .pinDirection = kGPIO_DigitalOutput,
        .outputLogic = 0U
    };
    /* Initialize GPIO functionality on pin PTB5 (pin 21) */
    GPIO_PinInit(BOARD_INITPINS_DAC_CLOCK_GPIO_PORT, BOARD_INITPINS_DAC_CLOCK_PIN, &DAC_CLOCK_config);

    gpio_pin_config_t DAC_SD_X_COEFF_config = {
        .pinDirection = kGPIO_DigitalOutput,
        .outputLogic = 0U
    };
    /* Initialize GPIO functionality on pin PTB6 (pin 20) */
    GPIO_PinInit(BOARD_INITPINS_DAC_SD_X_COEFF_GPIO_PORT, BOARD_INITPINS_DAC_SD_X_COEFF_PIN, &DAC_SD_X_COEFF_config);

    gpio_pin_config_t DAC_SD_Y_COEFF_config = {
        .pinDirection = kGPIO_DigitalOutput,
        .outputLogic = 0U
    };
    /* Initialize GPIO functionality on pin PTB30 (pin 4) */
    GPIO_PinInit(BOARD_INITPINS_DAC_SD_Y_COEFF_GPIO_PORT, BOARD_INITPINS_DAC_SD_Y_COEFF_PIN, &DAC_SD_Y_COEFF_config);
    /* pin 64,63 is configured as UART1_RX, UART1_TX */
    PORT_SetPinSelect(kPORT_UART1, kPORT_UART1_RXPTC7_TXPTC6);
}
/***********************************************************************************************************************
 * EOF
 **********************************************************************************************************************/
